trigger:
- main

resources:
- repo: self


variables:
- group: GitHub-Secrets

- name: dockerRegistryServiceConnection
  value: '4ca1b796-fefa-4a30-bdb2-151c27da6be6'

- name: imageRepository
  value: 'app1nginxaks'

- name: containerRegistry
  value: 'akscontaineregistrydemo.azurecr.io'

- name: dockerfilePath
  value: '**/Dockerfile'

- name: tag
  value: '$(Build.SourceVersion)'

- name: vmImageName
  value: 'ubuntu-latest'

stages:

- stage: Build

  displayName: Build and Push

  jobs:

  - job: Build

    displayName: Build Docker Image

    pool:

      vmImage: $(vmImageName)


    steps:


    # Checkout Application Repository
    - checkout: self
      persistCredentials: true
    
    - script: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 \
          -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
        yq --version
      displayName: Install yq


    # Build and Push Image to ACR

    - task: Docker@2

      displayName: Build and Push Image

      inputs:

        command: buildAndPush

        repository: $(imageRepository)

        dockerfile: $(dockerfilePath)

        containerRegistry: $(dockerRegistryServiceConnection)

        tags: |
          $(tag)



    - script: |
        set -e

        rm -rf gitops-repo

        git -c http.extraHeader="Authorization: Bearer $(GITHUB_PAT)" \
        clone https://github.com/nishadZC/gitops-repo.git

        cd gitops-repo/app1

        yq -i '
        .spec.template.spec.containers[0].image =
        "$(containerRegistry)/$(imageRepository):$(tag)"
        ' deployment.yml

        echo "Updated image:"
        yq '.spec.template.spec.containers[0].image' deployment.yml

        git config user.email "azurepipeline@gmail.com"
        git config user.name "Azure Pipeline"

        git add deployment.yml

        if git diff --cached --quiet; then
            echo "No manifest changes."
        else
            git commit -m "Deploy $(tag)"
            git push origin main
        fi
      displayName: Update GitOps Repository