trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: dockerRegistryServiceConnection
  value: '4ca1b796-fefa-4a30-bdb2-151c27da6be6'

- name: imageRepository
  value: app1nginxaks

- name: containerRegistry
  value: akscontaineregistrydemo.azurecr.io

- name: dockerfilePath
  value: '**/Dockerfile'

- name: tag
  value: $(Build.BuildId)

steps:

- checkout: self

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

# Trigger GitOps Pipeline
- bash: |

    echo "Triggering GitOps Pipeline..."

    curl -X POST \
      -u :$(System.AccessToken) \
      -H "Content-Type: application/json" \
      -d '{
        "templateParameters": {
          "imageTag": "$(Build.BuildId)"
        }
      }' \
      https://dev.azure.com/vinayaknishad/azure-devops-pipeline/_apis/pipelines/14/runs?api-version=7.1-preview.1

  displayName: Trigger GitOps Pipeline
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)